# Generated by Django 6.1 on 2026-08-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_hub_app', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
